# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Daily update dependencies

on:
  schedule:
  # At 00:00 UTC every day.
  - cron:  '00 00 * * *'
  repository_dispatch:
    types: update-dependencies

defaults:
  run:
    shell: pwsh

jobs:
  update-dotnet-preview:
    name: Update .NET nanoFramework dependencies
    timeout-minutes: 15
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      SOLUTION: 'nanoFramework.Hardware.Stm32.sln'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find packages folder
        id: find_packages
        run: |
          $solutionLocation = (Get-ChildItem -Path "$Env:GITHUB_WORKSPACE" -Include $Env:SOLUTION -Recurse)
          $packagesLocation = $solutionLocation[0].Directory.FullName+"\packages"
          echo "Found packages folder for solution at: $packagesLocation"
          echo "NUGET_PACKAGES=$packagesLocation" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Cache nano NuGets
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}

      - name: Update dependencies
        uses: nanoframework/nanodu@v1
        with:
          solutionsToCheck: ${{ env.SOLUTION }}
