# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Daily update dependencies

on:
  schedule:
  # At 00:00 UTC every day.
  - cron:  '00 00 * * *'
  repository_dispatch:
    types: update-dependencies

defaults:
  run:
    shell: pwsh

jobs:
  update-dotnet-preview:
    name: Update .NET nanoFramework dependencies
    timeout-minutes: 15
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      SOLUTION: 'nanoFramework.Hardware.Stm32.sln'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Update dependencies
        uses: nanoframework/nanodu@v1
        with:
          solutionsToCheck: ${{ env.SOLUTION }}
